// Copyright 2026 AxonOps Limited.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package audit

import (
	"context"
	"fmt"
	"sort"
)

// LabelInfo describes a sensitivity label defined in the taxonomy.
type LabelInfo struct {
	Name        string // label name, e.g., "pii"
	Description string // human-readable explanation
}

// FieldInfo describes a single field on an audit event type.
type FieldInfo struct {
	Name     string      // field name, e.g., "email"
	Labels   []LabelInfo // sensitivity labels on this field
	Required bool        // true if the field must be present
}

// CategoryInfo describes a category an event type belongs to.
type CategoryInfo struct {
	Severity *int   // category-level severity, nil if not set
	Name     string // category name, e.g., "write"
}

// Event represents a typed audit event with its event type, fields,
// and taxonomy metadata.
//
// # How to obtain an Event
//
// Consumers SHOULD NOT implement this interface directly. The library
// provides three construction paths, in decreasing order of
// preference:
//
//   - **Generated builders from audit-gen** (recommended): the
//     generated constructors take required fields as parameters and
//     expose optional fields as setter methods, giving compile-time
//     safety against [ErrMissingRequiredField] / [ErrUnknownField].
//     They also opt into the zero-extra-allocation fast path on the
//     hot enqueue route via an unexported sentinel — hand-rolled
//     implementations cannot.
//   - [NewEvent] — dynamic construction from a [Fields] map. Useful
//     for table-driven tests, middleware, or events whose shape is
//     determined at runtime.
//   - [NewEventKV] — variadic key/value form, e.g.
//     `NewEventKV("user_create", "id", 123, "ok", true)`. Convenient
//     for one-off events without a [Fields] literal.
//
// Implementations are generated by audit-gen for compile-time field
// safety. For dynamic use without code generation, see [NewEvent] —
// note that basic events are taxonomy-agnostic and return zero values
// for the metadata methods (Description / Categories / FieldInfoMap);
// pair them with [Auditor.Handle] when consumers need metadata
// access.
//
// The metadata methods support middleware and other consumers that
// receive an [Event] and need to introspect its declared shape (e.g.
// to redact sensitive fields, route by severity, or attach
// description text). Generated builders carry richer metadata than
// the interface exposes — concrete types add a typed
// `FieldInfo() <Event>Fields` method for compile-time field access;
// the interface's [FieldInfoMap] method returns the same data as a
// keyed map for dynamic introspection. This mirrors stdlib
// [reflect.Type.Field] (ordered) versus [reflect.Type.FieldByName]
// (keyed) — both shapes coexist and serve different access patterns.
//
// # Mutation contract
//
// The values returned by [Event.Categories] and [Event.FieldInfoMap]
// are READ-ONLY. Callers MUST NOT mutate the returned slice, map,
// or any pointer-typed field within them (e.g. `CategoryInfo.Severity`).
// Implementations are free to share cached values across calls — the
// receiver of an [Event] cannot tell whether it holds a snapshot or
// the live taxonomy state, so it must treat the data as immutable.
// To consume metadata mutably, copy first.
type Event interface {
	// EventType returns the event type name (e.g., "user_create").
	EventType() string
	// Fields returns the event's field key-value pairs.
	Fields() Fields
	// Description returns the event's human-readable description from
	// the taxonomy. Empty string for events constructed via [NewEvent]
	// or [NewEventKV] (which are taxonomy-agnostic).
	Description() string
	// Categories returns the categories this event belongs to, with
	// per-category severity. nil for events constructed via [NewEvent]
	// or [NewEventKV]. Read-only; callers MUST NOT mutate the slice
	// or its `*Severity` pointers.
	Categories() []CategoryInfo
	// FieldInfoMap returns the per-field metadata (name, sensitivity
	// labels, required flag) keyed by field name. nil for events
	// constructed via [NewEvent] or [NewEventKV]. Generated builders
	// also expose a typed `FieldInfo() <Event>Fields` method for
	// compile-time field access. Read-only; callers MUST NOT mutate
	// the map or its values.
	FieldInfoMap() map[string]FieldInfo
}

// basicEvent implements [Event] for consumers who do not use code
// generation. Created via [NewEvent].
type basicEvent struct {
	fields    Fields
	eventType string
}

// NewEvent creates an untyped audit event. Prefer generated typed
// builders from audit-gen for compile-time field safety. This function
// exists for consumers who construct events dynamically or do not use
// code generation.
//
// The returned [Event] is taxonomy-agnostic: [Event.Description],
// [Event.Categories], and [Event.FieldInfoMap] return zero values
// (empty string and nil). Consumers that need metadata access (e.g.
// middleware that redacts based on field sensitivity labels) should
// use [Auditor.Handle] — the handle resolves taxonomy metadata once
// at construction and exposes it via parallel methods. Generated
// typed builders also carry full metadata.
//
// Allocation note: each call allocates one basicEvent on the heap
// because the returned [Event] interface value forces the pointer to
// escape. For high-throughput callers whose event type is known but
// dynamic (from configuration, a database, or a plugin), prefer
// [EventHandle] — it pre-validates the event type once and emits
// without the per-call basicEvent allocation. See [Auditor.Handle]
// and [Auditor.MustHandle].
//
// For a side-by-side comparison of NewEvent, EventHandle, and
// generated builders with examples and benchmark numbers, see
// docs/event-emission-paths.md.
func NewEvent(eventType string, fields Fields) Event {
	return &basicEvent{
		eventType: eventType,
		fields:    fields,
	}
}

// Compile-time interface satisfaction check.
var _ Event = (*basicEvent)(nil)

func (e *basicEvent) EventType() string { return e.eventType }
func (e *basicEvent) Fields() Fields    { return e.fields }

// Description returns the empty string. basicEvent is
// taxonomy-agnostic; see the [NewEvent] godoc for the metadata-aware
// alternatives.
func (e *basicEvent) Description() string { return "" }

// Categories returns nil. basicEvent is taxonomy-agnostic; see the
// [NewEvent] godoc for the metadata-aware alternatives.
func (e *basicEvent) Categories() []CategoryInfo { return nil }

// FieldInfoMap returns nil. basicEvent is taxonomy-agnostic; see the
// [NewEvent] godoc for the metadata-aware alternatives.
func (e *basicEvent) FieldInfoMap() map[string]FieldInfo { return nil }

// NewEventKV creates an audit event from alternating key-value pairs,
// following the [log/slog] convention:
//
//	ev, err := audit.NewEventKV("user_create", "outcome", "success", "actor_id", "alice")
//	if err != nil {
//	    // Programmer error: odd number of args or non-string key.
//	    return err
//	}
//
// NewEventKV returns a non-nil error wrapping [ErrValidation] if
// keysAndValues has an odd number of elements or any key is not a
// string. For literal call sites (tests, examples, known-good kv
// pairs) use [MustNewEventKV] instead — it preserves the pre-#590
// panic-on-programmer-error contract and reads as a single-line
// expression at the call site.
//
// The returned [Event] is taxonomy-agnostic — see the [NewEvent]
// godoc for the metadata-method behaviour and alternatives that
// carry full metadata.
//
// Allocation note: NewEventKV allocates the intermediate [Fields] map
// plus the basicEvent returned by [NewEvent] — two heap allocations
// per call (plus any-boxing of non-string values). For high-throughput
// callers, prefer generated typed builders (zero caller-side
// allocations after warm-up) or [EventHandle] for dynamic event types.
//
// For a side-by-side comparison of NewEvent, EventHandle, and
// generated builders with examples and benchmark numbers, see
// docs/event-emission-paths.md.
func NewEventKV(eventType string, keysAndValues ...any) (Event, error) {
	if len(keysAndValues)%2 != 0 {
		return nil, fmt.Errorf("%w: NewEventKV requires even number of arguments, got %d",
			ErrValidation, len(keysAndValues))
	}
	fields := make(Fields, len(keysAndValues)/2)
	for i := 0; i < len(keysAndValues); i += 2 {
		key, ok := keysAndValues[i].(string)
		if !ok {
			return nil, fmt.Errorf("%w: NewEventKV key at index %d must be string, got %T",
				ErrValidation, i, keysAndValues[i])
		}
		fields[key] = keysAndValues[i+1]
	}
	return NewEvent(eventType, fields), nil
}

// MustNewEventKV is like [NewEventKV] but panics if keysAndValues is
// invalid. Intended for literal call sites (tests, examples,
// package-level initialisation) where the input is known at compile
// time and two-line error handling is pure noise:
//
//	logger.AuditEvent(audit.MustNewEventKV("user_create",
//	    "outcome", "success",
//	    "actor_id", "alice",
//	))
//
// Mirrors [regexp.MustCompile] / [template.Must] — the canonical Go
// pattern for configuration-time construction with compile-time-known
// input. Dynamic-input callers should use [NewEventKV] instead.
func MustNewEventKV(eventType string, keysAndValues ...any) Event {
	ev, err := NewEventKV(eventType, keysAndValues...)
	if err != nil {
		// err.Error() already starts with "audit: " via the wrapped
		// ErrValidation sentinel — no second prefix needed.
		panic(err.Error())
	}
	return ev
}

// EventHandle is a pre-validated reference to a registered event type.
// It is the recommended emission path when the event type is known at
// startup but not at compile time — for example, event type names
// pulled from configuration, a database, or a plugin registry.
//
// Obtain one handle per event type at startup via [Auditor.Handle]
// (returns an error) or [Auditor.MustHandle] (panics on unknown event
// type), cache it, and emit via [EventHandle.Audit] on each event.
// The handle validates the event type once at construction; per-event
// calls go straight into the audit pipeline without re-validating the
// name and without the basicEvent heap allocation paid by
// [NewEvent].
//
// For event types known at compile time, prefer generated typed
// builders from audit-gen — they add compile-time field safety and
// implement [FieldsDonor] for the zero-allocation drain-side fast
// path.
//
// For a side-by-side comparison of NewEvent, EventHandle, and
// generated builders with examples and benchmark numbers, see
// docs/event-emission-paths.md.
type EventHandle struct {
	auditor      *Auditor
	fieldInfoMap map[string]FieldInfo
	name         string
	description  string
	categories   []CategoryInfo
}

// Description returns the event type's description from the
// taxonomy. Resolved once at handle construction; cached.
func (e *EventHandle) Description() string { return e.description }

// Categories returns the event type's category memberships with
// per-category severity. Resolved once at handle construction;
// cached and shared across calls per the [Event] interface's
// read-only contract — callers MUST NOT mutate the slice or its
// `*Severity` pointers. To consume mutably, copy first.
func (e *EventHandle) Categories() []CategoryInfo {
	return e.categories
}

// FieldInfoMap returns the event type's per-field metadata keyed by
// field name. Resolved once at handle construction; cached. The
// returned map is the cached one; callers MUST NOT mutate it.
func (e *EventHandle) FieldInfoMap() map[string]FieldInfo {
	return e.fieldInfoMap
}

// resolveCategoryInfos walks the taxonomy to build the
// []CategoryInfo for an event type. Severity is read from the
// CategoryDef; nil if not set.
func resolveCategoryInfos(t *Taxonomy, def *EventDef) []CategoryInfo {
	if def == nil || len(def.Categories) == 0 {
		return nil
	}
	out := make([]CategoryInfo, 0, len(def.Categories))
	for _, name := range def.Categories {
		ci := CategoryInfo{Name: name}
		if cat, ok := t.Categories[name]; ok && cat != nil && cat.Severity != nil {
			sev := *cat.Severity
			ci.Severity = &sev
		}
		out = append(out, ci)
	}
	return out
}

// resolveFieldInfos walks the taxonomy to build the
// map[string]FieldInfo for an event type. Sensitivity labels come
// from EventDef.FieldLabels (already resolved by precomputeTaxonomy
// from explicit annotation + global mapping + regex patterns).
//
//nolint:gocognit,gocyclo,cyclop // single map walk over Required/Optional/FieldLabels — flat shape, not branching complexity
func resolveFieldInfos(t *Taxonomy, def *EventDef) map[string]FieldInfo {
	if def == nil {
		return nil
	}
	allFields := make(map[string]bool, len(def.Required)+len(def.Optional))
	for _, f := range def.Required {
		allFields[f] = true
	}
	for _, f := range def.Optional {
		if !allFields[f] {
			allFields[f] = false
		}
	}
	if len(allFields) == 0 {
		return nil
	}

	out := make(map[string]FieldInfo, len(allFields))
	for name, required := range allFields {
		fi := FieldInfo{Name: name, Required: required}
		if labels, ok := def.FieldLabels[name]; ok && len(labels) > 0 {
			lis := make([]LabelInfo, 0, len(labels))
			for label := range labels {
				li := LabelInfo{Name: label}
				if t.Sensitivity != nil {
					if sl, ok := t.Sensitivity.Labels[label]; ok && sl != nil {
						li.Description = sl.Description
					}
				}
				lis = append(lis, li)
			}
			// Sort by name so consumers and golden-file tests see a
			// deterministic order; the underlying FieldLabels map walk
			// is non-deterministic.
			sort.Slice(lis, func(i, j int) bool { return lis[i].Name < lis[j].Name })
			fi.Labels = lis
		}
		out[name] = fi
	}
	return out
}

// Audit emits an audit event using this handle's bound event type.
// Zero per-event caller-side allocations (no basicEvent
// construction, no [Event] interface escape) — the internal audit
// path is called directly. For the zero-drain-side-allocations fast
// path (the [FieldsDonor] contract), emit a generated typed builder
// directly via [Auditor.AuditEvent].
//
// Audit is a convenience wrapper around [EventHandle.AuditContext]
// with [context.Background]. Prefer the ctx-aware variant when you
// have a request-scoped context (e.g. from an HTTP handler) — see
// [Auditor.AuditEventContext] for the cancellation-point semantics.
func (e *EventHandle) Audit(fields Fields) error {
	return e.AuditContext(context.Background(), fields)
}

// AuditContext is the [context.Context]-aware variant of
// [EventHandle.Audit]. The handle's bound event type is preserved;
// only the cancellation-aware path differs. See
// [Auditor.AuditEventContext] for the ctx-checking semantics —
// AuditContext shares the same internal core via auditInternalCtx.
func (e *EventHandle) AuditContext(ctx context.Context, fields Fields) error {
	return e.auditor.auditInternalCtx(ctx, e.name, fields)
}

// AuditEvent emits an [Event] (typically a generated builder) using
// the auditor bound to this handle. Unlike [EventHandle.Audit], the
// event type is taken from evt.EventType(), not from the handle's
// bound type — the handle provides the auditor binding only. This
// method accepts any [Event] implementation, making it composable
// with code-generated typed builders.
//
// Allocation note: this method takes the standard [Auditor.AuditEvent]
// path. Allocation behaviour depends on evt: generated builders that
// implement [FieldsDonor] reach 0 drain-side allocs per event; plain
// [Event] values (including [NewEvent] output) pay the defensive-copy
// cost described in [docs/performance.md].
//
// AuditEvent is a convenience wrapper around
// [EventHandle.AuditEventContext] with [context.Background]. Prefer
// the ctx-aware variant when you have a request-scoped context.
func (e *EventHandle) AuditEvent(evt Event) error {
	return e.AuditEventContext(context.Background(), evt)
}

// AuditEventContext is the [context.Context]-aware variant of
// [EventHandle.AuditEvent]. The same auditor instance is used; ctx
// is threaded through to [Auditor.AuditEventContext].
func (e *EventHandle) AuditEventContext(ctx context.Context, evt Event) error {
	return e.auditor.AuditEventContext(ctx, evt)
}

// EventType returns the event type name this handle represents.
func (e *EventHandle) EventType() string {
	return e.name
}

// FieldsDonor is an optional extension interface that the audit
// pipeline checks via type assertion in [Auditor.AuditEvent]. When an
// [Event] also implements FieldsDonor, the auditor takes ownership of
// the [Fields] map returned by [Event.Fields] — no defensive copy.
//
// # Contract
//
// Implementers MUST NOT mutate or retain the returned Fields after
// [Event.Fields] is called by the auditor:
//
//   - The auditor merges standard-field defaults INTO the returned
//     map and the formatters then read from it across multiple
//     outputs.
//   - Re-using the same Event instance for a second [Auditor.AuditEvent]
//     call is undefined behaviour. The first call's defaults remain in
//     the map; subsequent calls would observe stale state.
//
// # Sentinel
//
// The unexported [donateFields] sentinel method prevents third-party
// implementation outside the audit-gen toolchain. Generated builders
// emit the sentinel; consumer-defined Event types and [NewEvent]
// stay on the defensive-copy slow path.
//
// See [docs/adr/0001-fields-ownership-contract.md] for the design
// rationale and benchmarks (#497).
type FieldsDonor interface {
	Event
	donateFields()
}

// auditEntry is the internal representation of an audit event as it
// travels through the async channel. It is not exported.
type auditEntry struct {
	fields    Fields
	eventType string
	// donated is true when fields was supplied by a [FieldsDonor]
	// (the caller's map). Pool-return must be skipped — the map
	// belongs to the donor, not the auditor's fieldsPool. donated is
	// false on the defensive-copy slow path; the existing pool-return
	// behaviour applies (#497).
	donated bool
}
