// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import (
	"time"

	"github.com/axonops/audit"
)

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	EventAuthFailure      = "auth_failure"
	EventHealthCheck      = "health_check"
	EventPermissionDenied = "permission_denied"
	EventUserCreate       = "user_create"
	EventUserUpdate       = "user_update"
)

// Category constants — use with Auditor.EnableCategory and
// Auditor.DisableCategory.
const (
	CategorySecurity = "security"
	CategoryWrite    = "write"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction     = "action"
	FieldActorID    = "actor_id"
	FieldActorUID   = "actor_uid"
	FieldComponent  = "component"
	FieldDestHost   = "dest_host"
	FieldDestIP     = "dest_ip"
	FieldDestPort   = "dest_port"
	FieldEndTime    = "end_time"
	FieldFileHash   = "file_hash"
	FieldFileName   = "file_name"
	FieldFilePath   = "file_path"
	FieldFileSize   = "file_size"
	FieldMessage    = "message"
	FieldMethod     = "method"
	FieldOutcome    = "outcome"
	FieldPath       = "path"
	FieldProtocol   = "protocol"
	FieldReason     = "reason"
	FieldReferrer   = "referrer"
	FieldRequestID  = "request_id"
	FieldResource   = "resource"
	FieldResourceID = "resource_id"
	FieldRole       = "role"
	FieldSessionID  = "session_id"
	FieldSourceHost = "source_host"
	FieldSourceIP   = "source_ip"
	FieldSourcePort = "source_port"
	FieldStartTime  = "start_time"
	FieldTargetID   = "target_id"
	FieldTargetRole = "target_role"
	FieldTargetType = "target_type"
	FieldTargetUID  = "target_uid"
	FieldTransport  = "transport"
	FieldUserAgent  = "user_agent"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventAuthFailure: {
		Required: []string{FieldActorID, FieldOutcome, FieldReason},
		Optional: []string{},
	},
	EventHealthCheck: {
		Required: []string{FieldActorID, FieldComponent, FieldOutcome},
		Optional: []string{},
	},
	EventPermissionDenied: {
		Required: []string{FieldActorID, FieldOutcome, FieldResource},
		Optional: []string{},
	},
	EventUserCreate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldResourceID},
	},
	EventUserUpdate: {
		Required: []string{FieldActorID, FieldOutcome},
		Optional: []string{FieldResourceID},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategorySecurity: {EventAuthFailure, EventPermissionDenied},
	CategoryWrite:    {EventUserCreate, EventUserUpdate},
}

// AuthFailureFields describes every field on [EventAuthFailure] events.
type AuthFailureFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Reason     audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// AuthFailureEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type AuthFailureEvent struct {
	fields audit.Fields
}

// NewAuthFailureEvent creates a EventAuthFailure event with required fields.
func NewAuthFailureEvent(actorID string, outcome string, reason string) *AuthFailureEvent {
	return &AuthFailureEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
		FieldReason:  reason,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *AuthFailureEvent) SetAction(v string) *AuthFailureEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *AuthFailureEvent) SetActorUID(v string) *AuthFailureEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *AuthFailureEvent) SetDestHost(v string) *AuthFailureEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *AuthFailureEvent) SetDestIP(v string) *AuthFailureEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *AuthFailureEvent) SetDestPort(v int) *AuthFailureEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *AuthFailureEvent) SetEndTime(v time.Time) *AuthFailureEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *AuthFailureEvent) SetFileHash(v string) *AuthFailureEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *AuthFailureEvent) SetFileName(v string) *AuthFailureEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *AuthFailureEvent) SetFilePath(v string) *AuthFailureEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *AuthFailureEvent) SetFileSize(v int) *AuthFailureEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *AuthFailureEvent) SetMessage(v string) *AuthFailureEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *AuthFailureEvent) SetMethod(v string) *AuthFailureEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *AuthFailureEvent) SetPath(v string) *AuthFailureEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *AuthFailureEvent) SetProtocol(v string) *AuthFailureEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *AuthFailureEvent) SetReferrer(v string) *AuthFailureEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *AuthFailureEvent) SetRequestID(v string) *AuthFailureEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *AuthFailureEvent) SetRole(v string) *AuthFailureEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *AuthFailureEvent) SetSessionID(v string) *AuthFailureEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *AuthFailureEvent) SetSourceHost(v string) *AuthFailureEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *AuthFailureEvent) SetSourceIP(v string) *AuthFailureEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *AuthFailureEvent) SetSourcePort(v int) *AuthFailureEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *AuthFailureEvent) SetStartTime(v time.Time) *AuthFailureEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *AuthFailureEvent) SetTargetID(v string) *AuthFailureEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *AuthFailureEvent) SetTargetRole(v string) *AuthFailureEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *AuthFailureEvent) SetTargetType(v string) *AuthFailureEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *AuthFailureEvent) SetTargetUID(v string) *AuthFailureEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *AuthFailureEvent) SetTransport(v string) *AuthFailureEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *AuthFailureEvent) SetUserAgent(v string) *AuthFailureEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *AuthFailureEvent) EventType() string { return EventAuthFailure }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *AuthFailureEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *AuthFailureEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *AuthFailureEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *AuthFailureEvent) FieldInfo() AuthFailureFields {
	return AuthFailureFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Reason:     audit.FieldInfo{Name: FieldReason, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *AuthFailureEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [AuthFailureFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *AuthFailureEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldReason:     {Name: FieldReason, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// HealthCheckFields describes every field on [EventHealthCheck] events.
type HealthCheckFields struct {
	ActorID    audit.FieldInfo // required
	Component  audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// HealthCheckEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type HealthCheckEvent struct {
	fields audit.Fields
}

// NewHealthCheckEvent creates a EventHealthCheck event with required fields.
func NewHealthCheckEvent(actorID string, component string, outcome string) *HealthCheckEvent {
	return &HealthCheckEvent{fields: audit.Fields{
		FieldActorID:   actorID,
		FieldComponent: component,
		FieldOutcome:   outcome,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *HealthCheckEvent) SetAction(v string) *HealthCheckEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *HealthCheckEvent) SetActorUID(v string) *HealthCheckEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *HealthCheckEvent) SetDestHost(v string) *HealthCheckEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *HealthCheckEvent) SetDestIP(v string) *HealthCheckEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *HealthCheckEvent) SetDestPort(v int) *HealthCheckEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *HealthCheckEvent) SetEndTime(v time.Time) *HealthCheckEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *HealthCheckEvent) SetFileHash(v string) *HealthCheckEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *HealthCheckEvent) SetFileName(v string) *HealthCheckEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *HealthCheckEvent) SetFilePath(v string) *HealthCheckEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *HealthCheckEvent) SetFileSize(v int) *HealthCheckEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *HealthCheckEvent) SetMessage(v string) *HealthCheckEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *HealthCheckEvent) SetMethod(v string) *HealthCheckEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *HealthCheckEvent) SetPath(v string) *HealthCheckEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *HealthCheckEvent) SetProtocol(v string) *HealthCheckEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *HealthCheckEvent) SetReason(v string) *HealthCheckEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *HealthCheckEvent) SetReferrer(v string) *HealthCheckEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *HealthCheckEvent) SetRequestID(v string) *HealthCheckEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *HealthCheckEvent) SetRole(v string) *HealthCheckEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *HealthCheckEvent) SetSessionID(v string) *HealthCheckEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *HealthCheckEvent) SetSourceHost(v string) *HealthCheckEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *HealthCheckEvent) SetSourceIP(v string) *HealthCheckEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *HealthCheckEvent) SetSourcePort(v int) *HealthCheckEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *HealthCheckEvent) SetStartTime(v time.Time) *HealthCheckEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *HealthCheckEvent) SetTargetID(v string) *HealthCheckEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *HealthCheckEvent) SetTargetRole(v string) *HealthCheckEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *HealthCheckEvent) SetTargetType(v string) *HealthCheckEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *HealthCheckEvent) SetTargetUID(v string) *HealthCheckEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *HealthCheckEvent) SetTransport(v string) *HealthCheckEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *HealthCheckEvent) SetUserAgent(v string) *HealthCheckEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *HealthCheckEvent) EventType() string { return EventHealthCheck }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *HealthCheckEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *HealthCheckEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *HealthCheckEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *HealthCheckEvent) FieldInfo() HealthCheckFields {
	return HealthCheckFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Component:  audit.FieldInfo{Name: FieldComponent, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *HealthCheckEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [HealthCheckFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *HealthCheckEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldComponent:  {Name: FieldComponent, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// PermissionDeniedFields describes every field on [EventPermissionDenied] events.
type PermissionDeniedFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Resource   audit.FieldInfo // required
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// PermissionDeniedEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type PermissionDeniedEvent struct {
	fields audit.Fields
}

// NewPermissionDeniedEvent creates a EventPermissionDenied event with required fields.
func NewPermissionDeniedEvent(actorID string, outcome string, resource string) *PermissionDeniedEvent {
	return &PermissionDeniedEvent{fields: audit.Fields{
		FieldActorID:  actorID,
		FieldOutcome:  outcome,
		FieldResource: resource,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *PermissionDeniedEvent) SetAction(v string) *PermissionDeniedEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *PermissionDeniedEvent) SetActorUID(v string) *PermissionDeniedEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *PermissionDeniedEvent) SetDestHost(v string) *PermissionDeniedEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *PermissionDeniedEvent) SetDestIP(v string) *PermissionDeniedEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *PermissionDeniedEvent) SetDestPort(v int) *PermissionDeniedEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *PermissionDeniedEvent) SetEndTime(v time.Time) *PermissionDeniedEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *PermissionDeniedEvent) SetFileHash(v string) *PermissionDeniedEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *PermissionDeniedEvent) SetFileName(v string) *PermissionDeniedEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *PermissionDeniedEvent) SetFilePath(v string) *PermissionDeniedEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *PermissionDeniedEvent) SetFileSize(v int) *PermissionDeniedEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *PermissionDeniedEvent) SetMessage(v string) *PermissionDeniedEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *PermissionDeniedEvent) SetMethod(v string) *PermissionDeniedEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *PermissionDeniedEvent) SetPath(v string) *PermissionDeniedEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *PermissionDeniedEvent) SetProtocol(v string) *PermissionDeniedEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *PermissionDeniedEvent) SetReason(v string) *PermissionDeniedEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *PermissionDeniedEvent) SetReferrer(v string) *PermissionDeniedEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *PermissionDeniedEvent) SetRequestID(v string) *PermissionDeniedEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *PermissionDeniedEvent) SetRole(v string) *PermissionDeniedEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *PermissionDeniedEvent) SetSessionID(v string) *PermissionDeniedEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *PermissionDeniedEvent) SetSourceHost(v string) *PermissionDeniedEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *PermissionDeniedEvent) SetSourceIP(v string) *PermissionDeniedEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *PermissionDeniedEvent) SetSourcePort(v int) *PermissionDeniedEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *PermissionDeniedEvent) SetStartTime(v time.Time) *PermissionDeniedEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *PermissionDeniedEvent) SetTargetID(v string) *PermissionDeniedEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *PermissionDeniedEvent) SetTargetRole(v string) *PermissionDeniedEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *PermissionDeniedEvent) SetTargetType(v string) *PermissionDeniedEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *PermissionDeniedEvent) SetTargetUID(v string) *PermissionDeniedEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *PermissionDeniedEvent) SetTransport(v string) *PermissionDeniedEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *PermissionDeniedEvent) SetUserAgent(v string) *PermissionDeniedEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *PermissionDeniedEvent) EventType() string { return EventPermissionDenied }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *PermissionDeniedEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *PermissionDeniedEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *PermissionDeniedEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *PermissionDeniedEvent) FieldInfo() PermissionDeniedFields {
	return PermissionDeniedFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Resource:   audit.FieldInfo{Name: FieldResource, Required: true},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *PermissionDeniedEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategorySecurity},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [PermissionDeniedFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *PermissionDeniedEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldResource:   {Name: FieldResource, Required: true},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// UserCreateFields describes every field on [EventUserCreate] events.
type UserCreateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	ResourceID audit.FieldInfo // optional
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserCreateEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserCreateEvent struct {
	fields audit.Fields
}

// NewUserCreateEvent creates a EventUserCreate event with required fields.
func NewUserCreateEvent(actorID string, outcome string) *UserCreateEvent {
	return &UserCreateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetResourceID sets the FieldResourceID field.
func (e *UserCreateEvent) SetResourceID(v string) *UserCreateEvent {
	e.fields[FieldResourceID] = v
	return e
}

// SetAction sets the reserved standard field "action".
func (e *UserCreateEvent) SetAction(v string) *UserCreateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserCreateEvent) SetActorUID(v string) *UserCreateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserCreateEvent) SetDestHost(v string) *UserCreateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserCreateEvent) SetDestIP(v string) *UserCreateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserCreateEvent) SetDestPort(v int) *UserCreateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserCreateEvent) SetEndTime(v time.Time) *UserCreateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserCreateEvent) SetFileHash(v string) *UserCreateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserCreateEvent) SetFileName(v string) *UserCreateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserCreateEvent) SetFilePath(v string) *UserCreateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserCreateEvent) SetFileSize(v int) *UserCreateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserCreateEvent) SetMessage(v string) *UserCreateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserCreateEvent) SetMethod(v string) *UserCreateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserCreateEvent) SetPath(v string) *UserCreateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserCreateEvent) SetProtocol(v string) *UserCreateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserCreateEvent) SetReason(v string) *UserCreateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserCreateEvent) SetReferrer(v string) *UserCreateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserCreateEvent) SetRequestID(v string) *UserCreateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserCreateEvent) SetRole(v string) *UserCreateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserCreateEvent) SetSessionID(v string) *UserCreateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserCreateEvent) SetSourceHost(v string) *UserCreateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserCreateEvent) SetSourceIP(v string) *UserCreateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserCreateEvent) SetSourcePort(v int) *UserCreateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserCreateEvent) SetStartTime(v time.Time) *UserCreateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *UserCreateEvent) SetTargetID(v string) *UserCreateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserCreateEvent) SetTargetRole(v string) *UserCreateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *UserCreateEvent) SetTargetType(v string) *UserCreateEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserCreateEvent) SetTargetUID(v string) *UserCreateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserCreateEvent) SetTransport(v string) *UserCreateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserCreateEvent) SetUserAgent(v string) *UserCreateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserCreateEvent) EventType() string { return EventUserCreate }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *UserCreateEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *UserCreateEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *UserCreateEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserCreateEvent) FieldInfo() UserCreateFields {
	return UserCreateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		ResourceID: audit.FieldInfo{Name: FieldResourceID},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserCreateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [UserCreateFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *UserCreateEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldResourceID: {Name: FieldResourceID},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}

// UserUpdateFields describes every field on [EventUserUpdate] events.
type UserUpdateFields struct {
	ActorID    audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	ResourceID audit.FieldInfo // optional
	Action     audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Method     audit.FieldInfo // reserved standard
	Path       audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// UserUpdateEvent builds a type-safe audit event.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type UserUpdateEvent struct {
	fields audit.Fields
}

// NewUserUpdateEvent creates a EventUserUpdate event with required fields.
func NewUserUpdateEvent(actorID string, outcome string) *UserUpdateEvent {
	return &UserUpdateEvent{fields: audit.Fields{
		FieldActorID: actorID,
		FieldOutcome: outcome,
	}}
}

// SetResourceID sets the FieldResourceID field.
func (e *UserUpdateEvent) SetResourceID(v string) *UserUpdateEvent {
	e.fields[FieldResourceID] = v
	return e
}

// SetAction sets the reserved standard field "action".
func (e *UserUpdateEvent) SetAction(v string) *UserUpdateEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *UserUpdateEvent) SetActorUID(v string) *UserUpdateEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *UserUpdateEvent) SetDestHost(v string) *UserUpdateEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *UserUpdateEvent) SetDestIP(v string) *UserUpdateEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *UserUpdateEvent) SetDestPort(v int) *UserUpdateEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *UserUpdateEvent) SetEndTime(v time.Time) *UserUpdateEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *UserUpdateEvent) SetFileHash(v string) *UserUpdateEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *UserUpdateEvent) SetFileName(v string) *UserUpdateEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *UserUpdateEvent) SetFilePath(v string) *UserUpdateEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *UserUpdateEvent) SetFileSize(v int) *UserUpdateEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *UserUpdateEvent) SetMessage(v string) *UserUpdateEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *UserUpdateEvent) SetMethod(v string) *UserUpdateEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *UserUpdateEvent) SetPath(v string) *UserUpdateEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *UserUpdateEvent) SetProtocol(v string) *UserUpdateEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *UserUpdateEvent) SetReason(v string) *UserUpdateEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *UserUpdateEvent) SetReferrer(v string) *UserUpdateEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *UserUpdateEvent) SetRequestID(v string) *UserUpdateEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *UserUpdateEvent) SetRole(v string) *UserUpdateEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *UserUpdateEvent) SetSessionID(v string) *UserUpdateEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *UserUpdateEvent) SetSourceHost(v string) *UserUpdateEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *UserUpdateEvent) SetSourceIP(v string) *UserUpdateEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *UserUpdateEvent) SetSourcePort(v int) *UserUpdateEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *UserUpdateEvent) SetStartTime(v time.Time) *UserUpdateEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *UserUpdateEvent) SetTargetID(v string) *UserUpdateEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *UserUpdateEvent) SetTargetRole(v string) *UserUpdateEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *UserUpdateEvent) SetTargetType(v string) *UserUpdateEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *UserUpdateEvent) SetTargetUID(v string) *UserUpdateEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *UserUpdateEvent) SetTransport(v string) *UserUpdateEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *UserUpdateEvent) SetUserAgent(v string) *UserUpdateEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *UserUpdateEvent) EventType() string { return EventUserUpdate }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *UserUpdateEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *UserUpdateEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *UserUpdateEvent) Description() string { return "" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *UserUpdateEvent) FieldInfo() UserUpdateFields {
	return UserUpdateFields{
		ActorID:    audit.FieldInfo{Name: FieldActorID, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		ResourceID: audit.FieldInfo{Name: FieldResourceID},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Method:     audit.FieldInfo{Name: FieldMethod},
		Path:       audit.FieldInfo{Name: FieldPath},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *UserUpdateEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryWrite},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [UserUpdateFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *UserUpdateEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldActorID:    {Name: FieldActorID, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldResourceID: {Name: FieldResourceID},
		FieldAction:     {Name: FieldAction},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldMethod:     {Name: FieldMethod},
		FieldPath:       {Name: FieldPath},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}
