// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import (
	"time"

	"github.com/axonops/audit"
)

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventHTTPRequest — An HTTP request was processed
	EventHTTPRequest = "http_request"
)

// Category constants — use with Auditor.EnableCategory and
// Auditor.DisableCategory.
const (
	CategoryAccess = "access"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction     = "action"
	FieldActorID    = "actor_id"
	FieldActorUID   = "actor_uid"
	FieldDestHost   = "dest_host"
	FieldDestIP     = "dest_ip"
	FieldDestPort   = "dest_port"
	FieldDurationMS = "duration_ms"
	FieldEndTime    = "end_time"
	FieldFileHash   = "file_hash"
	FieldFileName   = "file_name"
	FieldFilePath   = "file_path"
	FieldFileSize   = "file_size"
	FieldMessage    = "message"
	FieldMethod     = "method"
	FieldOutcome    = "outcome"
	FieldPath       = "path"
	FieldProtocol   = "protocol"
	FieldReason     = "reason"
	FieldReferrer   = "referrer"
	FieldRequestID  = "request_id"
	FieldRole       = "role"
	FieldSessionID  = "session_id"
	FieldSourceHost = "source_host"
	FieldSourceIP   = "source_ip"
	FieldSourcePort = "source_port"
	FieldStartTime  = "start_time"
	FieldStatusCode = "status_code"
	FieldTargetID   = "target_id"
	FieldTargetRole = "target_role"
	FieldTargetType = "target_type"
	FieldTargetUID  = "target_uid"
	FieldTransport  = "transport"
	FieldUserAgent  = "user_agent"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventHTTPRequest: {
		Required: []string{FieldMethod, FieldOutcome, FieldPath},
		Optional: []string{FieldDurationMS, FieldStatusCode},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryAccess: {EventHTTPRequest},
}

// HTTPRequestFields describes every field on [EventHTTPRequest] events.
type HTTPRequestFields struct {
	Method     audit.FieldInfo // required
	Outcome    audit.FieldInfo // required
	Path       audit.FieldInfo // required
	DurationMS audit.FieldInfo // optional
	StatusCode audit.FieldInfo // optional
	Action     audit.FieldInfo // reserved standard
	ActorID    audit.FieldInfo // reserved standard
	ActorUID   audit.FieldInfo // reserved standard
	DestHost   audit.FieldInfo // reserved standard
	DestIP     audit.FieldInfo // reserved standard
	DestPort   audit.FieldInfo // reserved standard
	EndTime    audit.FieldInfo // reserved standard
	FileHash   audit.FieldInfo // reserved standard
	FileName   audit.FieldInfo // reserved standard
	FilePath   audit.FieldInfo // reserved standard
	FileSize   audit.FieldInfo // reserved standard
	Message    audit.FieldInfo // reserved standard
	Protocol   audit.FieldInfo // reserved standard
	Reason     audit.FieldInfo // reserved standard
	Referrer   audit.FieldInfo // reserved standard
	RequestID  audit.FieldInfo // reserved standard
	Role       audit.FieldInfo // reserved standard
	SessionID  audit.FieldInfo // reserved standard
	SourceHost audit.FieldInfo // reserved standard
	SourceIP   audit.FieldInfo // reserved standard
	SourcePort audit.FieldInfo // reserved standard
	StartTime  audit.FieldInfo // reserved standard
	TargetID   audit.FieldInfo // reserved standard
	TargetRole audit.FieldInfo // reserved standard
	TargetType audit.FieldInfo // reserved standard
	TargetUID  audit.FieldInfo // reserved standard
	Transport  audit.FieldInfo // reserved standard
	UserAgent  audit.FieldInfo // reserved standard
}

// HTTPRequestEvent builds a type-safe audit event: An HTTP request was processed.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type HTTPRequestEvent struct {
	fields audit.Fields
}

// NewHTTPRequestEvent creates a EventHTTPRequest event with required fields.
func NewHTTPRequestEvent(method string, outcome string, path string) *HTTPRequestEvent {
	return &HTTPRequestEvent{fields: audit.Fields{
		FieldMethod:  method,
		FieldOutcome: outcome,
		FieldPath:    path,
	}}
}

// SetDurationMS sets the FieldDurationMS field.
func (e *HTTPRequestEvent) SetDurationMS(v string) *HTTPRequestEvent {
	e.fields[FieldDurationMS] = v
	return e
}

// SetStatusCode sets the FieldStatusCode field.
func (e *HTTPRequestEvent) SetStatusCode(v string) *HTTPRequestEvent {
	e.fields[FieldStatusCode] = v
	return e
}

// SetAction sets the reserved standard field "action".
func (e *HTTPRequestEvent) SetAction(v string) *HTTPRequestEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorID sets the reserved standard field "actor_id".
func (e *HTTPRequestEvent) SetActorID(v string) *HTTPRequestEvent {
	e.fields[FieldActorID] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *HTTPRequestEvent) SetActorUID(v string) *HTTPRequestEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *HTTPRequestEvent) SetDestHost(v string) *HTTPRequestEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *HTTPRequestEvent) SetDestIP(v string) *HTTPRequestEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *HTTPRequestEvent) SetDestPort(v int) *HTTPRequestEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *HTTPRequestEvent) SetEndTime(v time.Time) *HTTPRequestEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *HTTPRequestEvent) SetFileHash(v string) *HTTPRequestEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *HTTPRequestEvent) SetFileName(v string) *HTTPRequestEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *HTTPRequestEvent) SetFilePath(v string) *HTTPRequestEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *HTTPRequestEvent) SetFileSize(v int) *HTTPRequestEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *HTTPRequestEvent) SetMessage(v string) *HTTPRequestEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *HTTPRequestEvent) SetProtocol(v string) *HTTPRequestEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *HTTPRequestEvent) SetReason(v string) *HTTPRequestEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *HTTPRequestEvent) SetReferrer(v string) *HTTPRequestEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *HTTPRequestEvent) SetRequestID(v string) *HTTPRequestEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *HTTPRequestEvent) SetRole(v string) *HTTPRequestEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *HTTPRequestEvent) SetSessionID(v string) *HTTPRequestEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *HTTPRequestEvent) SetSourceHost(v string) *HTTPRequestEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *HTTPRequestEvent) SetSourceIP(v string) *HTTPRequestEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *HTTPRequestEvent) SetSourcePort(v int) *HTTPRequestEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *HTTPRequestEvent) SetStartTime(v time.Time) *HTTPRequestEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *HTTPRequestEvent) SetTargetID(v string) *HTTPRequestEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *HTTPRequestEvent) SetTargetRole(v string) *HTTPRequestEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *HTTPRequestEvent) SetTargetType(v string) *HTTPRequestEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *HTTPRequestEvent) SetTargetUID(v string) *HTTPRequestEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *HTTPRequestEvent) SetTransport(v string) *HTTPRequestEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *HTTPRequestEvent) SetUserAgent(v string) *HTTPRequestEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *HTTPRequestEvent) EventType() string { return EventHTTPRequest }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *HTTPRequestEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *HTTPRequestEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *HTTPRequestEvent) Description() string { return "An HTTP request was processed" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *HTTPRequestEvent) FieldInfo() HTTPRequestFields {
	return HTTPRequestFields{
		Method:     audit.FieldInfo{Name: FieldMethod, Required: true},
		Outcome:    audit.FieldInfo{Name: FieldOutcome, Required: true},
		Path:       audit.FieldInfo{Name: FieldPath, Required: true},
		DurationMS: audit.FieldInfo{Name: FieldDurationMS},
		StatusCode: audit.FieldInfo{Name: FieldStatusCode},
		Action:     audit.FieldInfo{Name: FieldAction},
		ActorID:    audit.FieldInfo{Name: FieldActorID},
		ActorUID:   audit.FieldInfo{Name: FieldActorUID},
		DestHost:   audit.FieldInfo{Name: FieldDestHost},
		DestIP:     audit.FieldInfo{Name: FieldDestIP},
		DestPort:   audit.FieldInfo{Name: FieldDestPort},
		EndTime:    audit.FieldInfo{Name: FieldEndTime},
		FileHash:   audit.FieldInfo{Name: FieldFileHash},
		FileName:   audit.FieldInfo{Name: FieldFileName},
		FilePath:   audit.FieldInfo{Name: FieldFilePath},
		FileSize:   audit.FieldInfo{Name: FieldFileSize},
		Message:    audit.FieldInfo{Name: FieldMessage},
		Protocol:   audit.FieldInfo{Name: FieldProtocol},
		Reason:     audit.FieldInfo{Name: FieldReason},
		Referrer:   audit.FieldInfo{Name: FieldReferrer},
		RequestID:  audit.FieldInfo{Name: FieldRequestID},
		Role:       audit.FieldInfo{Name: FieldRole},
		SessionID:  audit.FieldInfo{Name: FieldSessionID},
		SourceHost: audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:   audit.FieldInfo{Name: FieldSourceIP},
		SourcePort: audit.FieldInfo{Name: FieldSourcePort},
		StartTime:  audit.FieldInfo{Name: FieldStartTime},
		TargetID:   audit.FieldInfo{Name: FieldTargetID},
		TargetRole: audit.FieldInfo{Name: FieldTargetRole},
		TargetType: audit.FieldInfo{Name: FieldTargetType},
		TargetUID:  audit.FieldInfo{Name: FieldTargetUID},
		Transport:  audit.FieldInfo{Name: FieldTransport},
		UserAgent:  audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *HTTPRequestEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryAccess},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [HTTPRequestFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *HTTPRequestEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldMethod:     {Name: FieldMethod, Required: true},
		FieldOutcome:    {Name: FieldOutcome, Required: true},
		FieldPath:       {Name: FieldPath, Required: true},
		FieldDurationMS: {Name: FieldDurationMS},
		FieldStatusCode: {Name: FieldStatusCode},
		FieldAction:     {Name: FieldAction},
		FieldActorID:    {Name: FieldActorID},
		FieldActorUID:   {Name: FieldActorUID},
		FieldDestHost:   {Name: FieldDestHost},
		FieldDestIP:     {Name: FieldDestIP},
		FieldDestPort:   {Name: FieldDestPort},
		FieldEndTime:    {Name: FieldEndTime},
		FieldFileHash:   {Name: FieldFileHash},
		FieldFileName:   {Name: FieldFileName},
		FieldFilePath:   {Name: FieldFilePath},
		FieldFileSize:   {Name: FieldFileSize},
		FieldMessage:    {Name: FieldMessage},
		FieldProtocol:   {Name: FieldProtocol},
		FieldReason:     {Name: FieldReason},
		FieldReferrer:   {Name: FieldReferrer},
		FieldRequestID:  {Name: FieldRequestID},
		FieldRole:       {Name: FieldRole},
		FieldSessionID:  {Name: FieldSessionID},
		FieldSourceHost: {Name: FieldSourceHost},
		FieldSourceIP:   {Name: FieldSourceIP},
		FieldSourcePort: {Name: FieldSourcePort},
		FieldStartTime:  {Name: FieldStartTime},
		FieldTargetID:   {Name: FieldTargetID},
		FieldTargetRole: {Name: FieldTargetRole},
		FieldTargetType: {Name: FieldTargetType},
		FieldTargetUID:  {Name: FieldTargetUID},
		FieldTransport:  {Name: FieldTransport},
		FieldUserAgent:  {Name: FieldUserAgent},
	}
}
