// Code generated by audit-gen from taxonomy.yaml; DO NOT EDIT.

//nolint:all // generated code — do not lint
package main

import (
	"time"

	"github.com/axonops/audit"
)

// Event type constants — use these instead of raw strings
// to get compile-time safety.
const (
	// EventHealthProbe — An external health check probed the service
	EventHealthProbe = "health_probe"
)

// Category constants — use with Auditor.EnableCategory and
// Auditor.DisableCategory.
const (
	CategoryOps = "ops"
)

// Field name constants — use in audit.Fields maps for
// compile-time typo prevention.
const (
	FieldAction      = "action"
	FieldActorID     = "actor_id"
	FieldActorUID    = "actor_uid"
	FieldDestHost    = "dest_host"
	FieldDestIP      = "dest_ip"
	FieldDestPort    = "dest_port"
	FieldEndTime     = "end_time"
	FieldFileHash    = "file_hash"
	FieldFileName    = "file_name"
	FieldFilePath    = "file_path"
	FieldFileSize    = "file_size"
	FieldMessage     = "message"
	FieldMethod      = "method"
	FieldOutcome     = "outcome"
	FieldPath        = "path"
	FieldProbeTarget = "probe_target"
	FieldProtocol    = "protocol"
	FieldReason      = "reason"
	FieldReferrer    = "referrer"
	FieldRequestID   = "request_id"
	FieldRole        = "role"
	FieldSessionID   = "session_id"
	FieldSourceHost  = "source_host"
	FieldSourceIP    = "source_ip"
	FieldSourcePort  = "source_port"
	FieldStartTime   = "start_time"
	FieldTargetID    = "target_id"
	FieldTargetRole  = "target_role"
	FieldTargetType  = "target_type"
	FieldTargetUID   = "target_uid"
	FieldTransport   = "transport"
	FieldUserAgent   = "user_agent"
)

// EventFields maps event types to their required and optional fields.
var EventFields = map[string]struct {
	Required []string
	Optional []string
}{
	EventHealthProbe: {
		Required: []string{FieldOutcome, FieldProbeTarget},
		Optional: []string{},
	},
}

// CategoryEvents maps category names to their member event types.
var CategoryEvents = map[string][]string{
	CategoryOps: {EventHealthProbe},
}

// HealthProbeFields describes every field on [EventHealthProbe] events.
type HealthProbeFields struct {
	Outcome     audit.FieldInfo // required
	ProbeTarget audit.FieldInfo // required
	Action      audit.FieldInfo // reserved standard
	ActorID     audit.FieldInfo // reserved standard
	ActorUID    audit.FieldInfo // reserved standard
	DestHost    audit.FieldInfo // reserved standard
	DestIP      audit.FieldInfo // reserved standard
	DestPort    audit.FieldInfo // reserved standard
	EndTime     audit.FieldInfo // reserved standard
	FileHash    audit.FieldInfo // reserved standard
	FileName    audit.FieldInfo // reserved standard
	FilePath    audit.FieldInfo // reserved standard
	FileSize    audit.FieldInfo // reserved standard
	Message     audit.FieldInfo // reserved standard
	Method      audit.FieldInfo // reserved standard
	Path        audit.FieldInfo // reserved standard
	Protocol    audit.FieldInfo // reserved standard
	Reason      audit.FieldInfo // reserved standard
	Referrer    audit.FieldInfo // reserved standard
	RequestID   audit.FieldInfo // reserved standard
	Role        audit.FieldInfo // reserved standard
	SessionID   audit.FieldInfo // reserved standard
	SourceHost  audit.FieldInfo // reserved standard
	SourceIP    audit.FieldInfo // reserved standard
	SourcePort  audit.FieldInfo // reserved standard
	StartTime   audit.FieldInfo // reserved standard
	TargetID    audit.FieldInfo // reserved standard
	TargetRole  audit.FieldInfo // reserved standard
	TargetType  audit.FieldInfo // reserved standard
	TargetUID   audit.FieldInfo // reserved standard
	Transport   audit.FieldInfo // reserved standard
	UserAgent   audit.FieldInfo // reserved standard
}

// HealthProbeEvent builds a type-safe audit event: An external health check probed the service.
// A builder is not safe for concurrent use. Calling a setter
// multiple times overwrites the previous value.
type HealthProbeEvent struct {
	fields audit.Fields
}

// NewHealthProbeEvent creates a EventHealthProbe event with required fields.
func NewHealthProbeEvent(outcome string, probeTarget string) *HealthProbeEvent {
	return &HealthProbeEvent{fields: audit.Fields{
		FieldOutcome:     outcome,
		FieldProbeTarget: probeTarget,
	}}
}

// SetAction sets the reserved standard field "action".
func (e *HealthProbeEvent) SetAction(v string) *HealthProbeEvent {
	e.fields[FieldAction] = v
	return e
}

// SetActorID sets the reserved standard field "actor_id".
func (e *HealthProbeEvent) SetActorID(v string) *HealthProbeEvent {
	e.fields[FieldActorID] = v
	return e
}

// SetActorUID sets the reserved standard field "actor_uid".
func (e *HealthProbeEvent) SetActorUID(v string) *HealthProbeEvent {
	e.fields[FieldActorUID] = v
	return e
}

// SetDestHost sets the reserved standard field "dest_host".
func (e *HealthProbeEvent) SetDestHost(v string) *HealthProbeEvent {
	e.fields[FieldDestHost] = v
	return e
}

// SetDestIP sets the reserved standard field "dest_ip".
func (e *HealthProbeEvent) SetDestIP(v string) *HealthProbeEvent {
	e.fields[FieldDestIP] = v
	return e
}

// SetDestPort sets the reserved standard field "dest_port".
func (e *HealthProbeEvent) SetDestPort(v int) *HealthProbeEvent {
	e.fields[FieldDestPort] = v
	return e
}

// SetEndTime sets the reserved standard field "end_time".
func (e *HealthProbeEvent) SetEndTime(v time.Time) *HealthProbeEvent {
	e.fields[FieldEndTime] = v
	return e
}

// SetFileHash sets the reserved standard field "file_hash".
func (e *HealthProbeEvent) SetFileHash(v string) *HealthProbeEvent {
	e.fields[FieldFileHash] = v
	return e
}

// SetFileName sets the reserved standard field "file_name".
func (e *HealthProbeEvent) SetFileName(v string) *HealthProbeEvent {
	e.fields[FieldFileName] = v
	return e
}

// SetFilePath sets the reserved standard field "file_path".
func (e *HealthProbeEvent) SetFilePath(v string) *HealthProbeEvent {
	e.fields[FieldFilePath] = v
	return e
}

// SetFileSize sets the reserved standard field "file_size".
func (e *HealthProbeEvent) SetFileSize(v int) *HealthProbeEvent {
	e.fields[FieldFileSize] = v
	return e
}

// SetMessage sets the reserved standard field "message".
func (e *HealthProbeEvent) SetMessage(v string) *HealthProbeEvent {
	e.fields[FieldMessage] = v
	return e
}

// SetMethod sets the reserved standard field "method".
func (e *HealthProbeEvent) SetMethod(v string) *HealthProbeEvent {
	e.fields[FieldMethod] = v
	return e
}

// SetPath sets the reserved standard field "path".
func (e *HealthProbeEvent) SetPath(v string) *HealthProbeEvent {
	e.fields[FieldPath] = v
	return e
}

// SetProtocol sets the reserved standard field "protocol".
func (e *HealthProbeEvent) SetProtocol(v string) *HealthProbeEvent {
	e.fields[FieldProtocol] = v
	return e
}

// SetReason sets the reserved standard field "reason".
func (e *HealthProbeEvent) SetReason(v string) *HealthProbeEvent {
	e.fields[FieldReason] = v
	return e
}

// SetReferrer sets the reserved standard field "referrer".
func (e *HealthProbeEvent) SetReferrer(v string) *HealthProbeEvent {
	e.fields[FieldReferrer] = v
	return e
}

// SetRequestID sets the reserved standard field "request_id".
func (e *HealthProbeEvent) SetRequestID(v string) *HealthProbeEvent {
	e.fields[FieldRequestID] = v
	return e
}

// SetRole sets the reserved standard field "role".
func (e *HealthProbeEvent) SetRole(v string) *HealthProbeEvent {
	e.fields[FieldRole] = v
	return e
}

// SetSessionID sets the reserved standard field "session_id".
func (e *HealthProbeEvent) SetSessionID(v string) *HealthProbeEvent {
	e.fields[FieldSessionID] = v
	return e
}

// SetSourceHost sets the reserved standard field "source_host".
func (e *HealthProbeEvent) SetSourceHost(v string) *HealthProbeEvent {
	e.fields[FieldSourceHost] = v
	return e
}

// SetSourceIP sets the reserved standard field "source_ip".
func (e *HealthProbeEvent) SetSourceIP(v string) *HealthProbeEvent {
	e.fields[FieldSourceIP] = v
	return e
}

// SetSourcePort sets the reserved standard field "source_port".
func (e *HealthProbeEvent) SetSourcePort(v int) *HealthProbeEvent {
	e.fields[FieldSourcePort] = v
	return e
}

// SetStartTime sets the reserved standard field "start_time".
func (e *HealthProbeEvent) SetStartTime(v time.Time) *HealthProbeEvent {
	e.fields[FieldStartTime] = v
	return e
}

// SetTargetID sets the reserved standard field "target_id".
func (e *HealthProbeEvent) SetTargetID(v string) *HealthProbeEvent {
	e.fields[FieldTargetID] = v
	return e
}

// SetTargetRole sets the reserved standard field "target_role".
func (e *HealthProbeEvent) SetTargetRole(v string) *HealthProbeEvent {
	e.fields[FieldTargetRole] = v
	return e
}

// SetTargetType sets the reserved standard field "target_type".
func (e *HealthProbeEvent) SetTargetType(v string) *HealthProbeEvent {
	e.fields[FieldTargetType] = v
	return e
}

// SetTargetUID sets the reserved standard field "target_uid".
func (e *HealthProbeEvent) SetTargetUID(v string) *HealthProbeEvent {
	e.fields[FieldTargetUID] = v
	return e
}

// SetTransport sets the reserved standard field "transport".
func (e *HealthProbeEvent) SetTransport(v string) *HealthProbeEvent {
	e.fields[FieldTransport] = v
	return e
}

// SetUserAgent sets the reserved standard field "user_agent".
func (e *HealthProbeEvent) SetUserAgent(v string) *HealthProbeEvent {
	e.fields[FieldUserAgent] = v
	return e
}

// EventType returns the event type name.
func (e *HealthProbeEvent) EventType() string { return EventHealthProbe }

// Fields returns the event fields for [audit.Auditor.AuditEvent].
//
// The returned [audit.Fields] map aliases the builder's internal
// storage. Callers MUST NOT mutate the returned map after the
// builder has been passed to AuditEvent — the auditor takes
// ownership via the [audit.FieldsDonor] fast path. Copy the map
// explicitly if you need a mutable view.
func (e *HealthProbeEvent) Fields() audit.Fields { return e.fields }

// donateFields satisfies [audit.FieldsDonor], opting this generated
// builder into the auditor's zero-extra-alloc fast path. The auditor
// takes ownership of the fields map returned by Fields() — generated
// builders MUST NOT mutate or reuse the builder after calling
// AuditEvent. See docs/adr/0001-fields-ownership-contract.md (#497).
func (e *HealthProbeEvent) donateFields() {}

// Description returns the taxonomy description.
func (e *HealthProbeEvent) Description() string { return "An external health check probed the service" }

// FieldInfo returns typed descriptors for every field on this event.
func (e *HealthProbeEvent) FieldInfo() HealthProbeFields {
	return HealthProbeFields{
		Outcome:     audit.FieldInfo{Name: FieldOutcome, Required: true},
		ProbeTarget: audit.FieldInfo{Name: FieldProbeTarget, Required: true},
		Action:      audit.FieldInfo{Name: FieldAction},
		ActorID:     audit.FieldInfo{Name: FieldActorID},
		ActorUID:    audit.FieldInfo{Name: FieldActorUID},
		DestHost:    audit.FieldInfo{Name: FieldDestHost},
		DestIP:      audit.FieldInfo{Name: FieldDestIP},
		DestPort:    audit.FieldInfo{Name: FieldDestPort},
		EndTime:     audit.FieldInfo{Name: FieldEndTime},
		FileHash:    audit.FieldInfo{Name: FieldFileHash},
		FileName:    audit.FieldInfo{Name: FieldFileName},
		FilePath:    audit.FieldInfo{Name: FieldFilePath},
		FileSize:    audit.FieldInfo{Name: FieldFileSize},
		Message:     audit.FieldInfo{Name: FieldMessage},
		Method:      audit.FieldInfo{Name: FieldMethod},
		Path:        audit.FieldInfo{Name: FieldPath},
		Protocol:    audit.FieldInfo{Name: FieldProtocol},
		Reason:      audit.FieldInfo{Name: FieldReason},
		Referrer:    audit.FieldInfo{Name: FieldReferrer},
		RequestID:   audit.FieldInfo{Name: FieldRequestID},
		Role:        audit.FieldInfo{Name: FieldRole},
		SessionID:   audit.FieldInfo{Name: FieldSessionID},
		SourceHost:  audit.FieldInfo{Name: FieldSourceHost},
		SourceIP:    audit.FieldInfo{Name: FieldSourceIP},
		SourcePort:  audit.FieldInfo{Name: FieldSourcePort},
		StartTime:   audit.FieldInfo{Name: FieldStartTime},
		TargetID:    audit.FieldInfo{Name: FieldTargetID},
		TargetRole:  audit.FieldInfo{Name: FieldTargetRole},
		TargetType:  audit.FieldInfo{Name: FieldTargetType},
		TargetUID:   audit.FieldInfo{Name: FieldTargetUID},
		Transport:   audit.FieldInfo{Name: FieldTransport},
		UserAgent:   audit.FieldInfo{Name: FieldUserAgent},
	}
}

// Categories returns the categories this event belongs to.
func (e *HealthProbeEvent) Categories() []audit.CategoryInfo {
	return []audit.CategoryInfo{
		{Name: CategoryOps},
	}
}

// FieldInfoMap returns per-field metadata keyed by field name. The
// data mirrors the typed [HealthProbeFields] returned by
// FieldInfo, exposed as a flat map to satisfy the dynamic
// [audit.Event] introspection contract (#597).
func (e *HealthProbeEvent) FieldInfoMap() map[string]audit.FieldInfo {
	return map[string]audit.FieldInfo{
		FieldOutcome:     {Name: FieldOutcome, Required: true},
		FieldProbeTarget: {Name: FieldProbeTarget, Required: true},
		FieldAction:      {Name: FieldAction},
		FieldActorID:     {Name: FieldActorID},
		FieldActorUID:    {Name: FieldActorUID},
		FieldDestHost:    {Name: FieldDestHost},
		FieldDestIP:      {Name: FieldDestIP},
		FieldDestPort:    {Name: FieldDestPort},
		FieldEndTime:     {Name: FieldEndTime},
		FieldFileHash:    {Name: FieldFileHash},
		FieldFileName:    {Name: FieldFileName},
		FieldFilePath:    {Name: FieldFilePath},
		FieldFileSize:    {Name: FieldFileSize},
		FieldMessage:     {Name: FieldMessage},
		FieldMethod:      {Name: FieldMethod},
		FieldPath:        {Name: FieldPath},
		FieldProtocol:    {Name: FieldProtocol},
		FieldReason:      {Name: FieldReason},
		FieldReferrer:    {Name: FieldReferrer},
		FieldRequestID:   {Name: FieldRequestID},
		FieldRole:        {Name: FieldRole},
		FieldSessionID:   {Name: FieldSessionID},
		FieldSourceHost:  {Name: FieldSourceHost},
		FieldSourceIP:    {Name: FieldSourceIP},
		FieldSourcePort:  {Name: FieldSourcePort},
		FieldStartTime:   {Name: FieldStartTime},
		FieldTargetID:    {Name: FieldTargetID},
		FieldTargetRole:  {Name: FieldTargetRole},
		FieldTargetType:  {Name: FieldTargetType},
		FieldTargetUID:   {Name: FieldTargetUID},
		FieldTransport:   {Name: FieldTransport},
		FieldUserAgent:   {Name: FieldUserAgent},
	}
}
